server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
  profiles:
    active: local
    
logging:
  level:
    org.springframework.cloud.netflix.zuul: debug
      
security:
  oauth2:
   resource:
      jwt:
        key-value: 123
      
