server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server

logging:
  level:
    org.springframework.cloud.netflix.zuul: debug
      
zuul:
  routes:  
    login:
      url: http://localhost:9014/api
      sensitiveHeaders:
      serviceId: login
    catalog:
      url: http://localhost:9016/api
      sensitiveHeaders:
      serviceId: catalog
    register:
      url: http://localhost:9012/api
      sensitiveHeaders:
      serviceId: register
    auth:
      sensitiveHeaders:
      url: http://localhost:9999/oauth
      serviceId: auth-server

  
security:
  oauth2:
   resource:
      jwt:
        key-value: 123
      
   client:
      accessTokenUri: http://localhost:8765/auth/token
      userAuthorizationUri: http://localhost:8765/auth/authorize
     
#security:
#  oauth2:
#    sso:
#      loginPath: /uaa/login      
#    client:
#      accessTokenUri: http://localhost:8765/uua/oauth/token
#      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#      clientId: acme
#      clientSecret: secret
#      clientAuthenticationScheme: form   
#    resource:
#      userInfoUri: http://localhost:9999/user
#      preferTokenInfo: false  
#  sessions: ALWAYS 
