server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
  profiles:
    active: local
    
logging:
  level:
    org.springframework.cloud.netflix.zuul: debug
      

zuul:
  routes:  
    login:
      url: http://localhost:9014/api
      sensitiveHeaders:
      serviceId: login
    catalog:
      url: http://localhost:9016/api
      sensitiveHeaders:
      serviceId: catalog
    orders:
      url: http://localhost:9018/orders
      sensitiveHeaders:
      serviceId: orders
    register:
      url: http://localhost:9012/api
      sensitiveHeaders:
      serviceId: register
    auth:
      sensitiveHeaders:
      url: http://localhost:9999/oauth
      serviceId: auth-server

security:
  oauth2:
   resource:
      jwt:
        key-value: 123
      
